### ISSUE TITLE
Cyby :3 signing the letter

### ISSUE THREAD

**Issue by siberland** [kenos1/save-suroi-together#11]
I strongly agree with the issues of Suroi's copying of Surviv being problematic, It seems there is very little idea of how to make a distinct game across the board.

Along with the sometimes poor moderation, which varies from non-existent to unreasonable at times, and also problematically the seemingly unchecked power. As a long time moderator I can assure you that my own behavior was unsavory and even rule breaking at times but at worst I've gotten a slap on the wrist, I believe that the fault lies with the leaders more than the soldiers though, a lack of strong direct leadership to hold moderators accountable. This will hopefully be resolved with the addition of more admins but only time can tell.
IIRC very rarely have I ever invoked rule 5 if ever, nor had I seen it invoked that often, however with lax auditing it is only a matter of time before someone snaps and goes power mad. Would stark (Who often muted people without reason at all) have been demoted if he didn't leak mod chat? You could probably mute/ban as many people as you want as long as you don't step on the toes of a higher up. 

That's most of what I really care about. Something that should also be included is that Suroi should openly support LGBTQ+ peoples by making any gender and sexual discrimination a bannable offense. For the most part Suroi has socially leaned towards this but it is never explicitly said in the rules, as a result you can openly discriminate against someones identity and get away with it.
Rule 1 is vague, and while rule 4 **hypothetically** blocks gender based discrimination, it doesn't protect LGB. And lax enforcement means that you probably could get away with it too. Intentional misgendering, Discriminatory bios, and loopholes have allowed people to get away with this behavior in the past and moderators refuse to enforce it seriously, hence why it should be written in the rules explictly.

Want to say something but it isn't allowed in the server? Put it in your bio, mods will not police it. You could say the most disgusting things that have come out of a persons psyche and as long as you arent  _explicitly_  saying something that's very illegal you'd be fine.

Many members get away with breaking rules, many members get away with having pages of violations. 
I'm sure favoritism does exist, I don't know if there is favoritism of specific members but long time more popular members generally get away with more. 
I'm not advocating for the banning of all member with multiple violations, that would be devastating to the server. I believe a good compromise is establishing a rule for a maximum amount of strikes you can get.
I myself was guilty of favoritism, and IIRC openly stated so too, I was not punished whatsoever.
 

I have a lot of respect for suroi moderation and leadership, however I disliked some parts near the end. I do hope the increased amount of higher ups and reduced veto power for the individual end up solving some of the problems. I have no comment on other development issues.

**Comment by siberland** [comment]
I would also like my name on the list of signatures.

**Comment by kenos1** [comment]
added, I'm also pinning this as this provides great insight
